// v2/mod.rs
/**
 * This file has been fully generated by AI and is very likely fallible.
 * 
 * The api is nearly identical to the V2 endpoint, 
 * except that it doesn't pretend to be secure with a non-validated TLS connection
 * And it sends maps via the websocket, rather than API.
 * 
 * CONTRIBUTORS: Please feel free to rework this, I don't use any V2 games enough to test it thoroughly.
*/

use std::{
    collections::HashMap,
    io,
    net::SocketAddr,
    sync::Arc,
};

use super::network::event_map::PatternLocation;
use crate::{
    log_err,
    mapping::{
        InputEventMessage, MapHandle,
        event::{Event, Frames, MaybeConst, Steps},
    },
};
use glam::Vec3;
use strum::IntoEnumIterator;

use futures_util::{SinkExt, StreamExt};
use tokio::net::TcpListener;
use tokio::sync::{mpsc, oneshot};
use tokio_util::sync::CancellationToken;
use tokio_websockets::Message;

const V2_TAG: &str = "Bhaptics_V2";

/// Const node parameters shared by every motor (matches maps/mod.rs).
const RADIUS: f32 = 0.0375;
const WEIGHT: f32 = 1.0;
/// Threshold under which a series is treated as a single constant.
const EPSILON: f32 = 0.001;
/// Engine tick period: events run at 100 Hz, i.e. one tick per 10 ms.
const MS_PER_TICK: u64 = 10;

/// Converts a millisecond duration into engine ticks (min 1, since
/// `Event::new` rejects a duration < 1 tick).
fn ms_to_ticks(ms: u64) -> u64 {
    (ms / MS_PER_TICK).max(1)
}

// ─── Server ──────────────────────────────────────────────────────────

pub async fn run_server(map: MapHandle, token: CancellationToken) {
    if let Err(e) = run_server_inner(map, token).await {
        log::error!("bHaptics V2 server error: {:?}", e);
    }
}

async fn run_server_inner(map: MapHandle, token: CancellationToken) -> io::Result<()> {
    let addr = SocketAddr::from(([127, 0, 0, 1], 15881));
    let listener = TcpListener::bind(&addr).await?;
    log::info!("bHaptics V2 API server started on {}", addr);

    loop {
        tokio::select! {
            _ = token.cancelled() => break,
            result = listener.accept() => {
                match result {
                    Ok((stream, _)) => {
                        let map = map.clone();
                        let child = token.child_token();
                        tokio::spawn(async move {
                            if let Err(e) = handle_connection(stream, map, child).await {
                                log::error!("V2 connection error: {:?}", e);
                            }
                        });
                    }
                    Err(e) => log::error!("V2 accept error: {:?}", e),
                }
            }
        }
    }

    log::info!("bHaptics V2 listener terminated.");
    Ok(())
}

// ─── Connection ──────────────────────────────────────────────────────

struct ConnectionState {
    app_id: String,
    app_name: String,
    /// Registered project payloads keyed by their string key.
    registered: HashMap<String, serde_json::Value>,
    /// Keys currently playing (reported back in the response payload).
    active_keys: Vec<String>,
}

async fn handle_connection(
    stream: tokio::net::TcpStream,
    map: MapHandle,
    token: CancellationToken,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let (request, ws_stream) = tokio_websockets::ServerBuilder::new()
        .accept(stream)
        .await?;

    let uri = request.uri().to_string();
    let (app_id, app_name) = parse_query_params(&uri);

    log::info!("V2 WebSocket connection: app_id={}, app_name={}", app_id, app_name);

    let (mut ws_write, mut ws_read) = ws_stream.split();
    let (tx, mut rx) = mpsc::unbounded_channel::<Message>();

    tokio::spawn(async move {
        while let Some(msg) = rx.recv().await {
            if ws_write.send(msg).await.is_err() {
                break;
            }
        }
    });

    // NOTE: the old node-insertion step (`insert_bhaptics_maps`) is gone — the
    // new event model bakes each motor's position directly into its `Steps`.
    let mut state = ConnectionState {
        app_id,
        app_name,
        registered: HashMap::new(),
        active_keys: Vec::new(),
    };

    loop {
        tokio::select! {
            _ = token.cancelled() => break,
            frame = ws_read.next() => {
                match frame {
                    Some(Ok(msg)) if msg.is_text() => {
                        let raw = msg.as_text().expect("checked is_text");
                        handle_player_request(raw, &mut state, &map, &tx).await;
                    }
                    Some(Ok(msg)) if msg.is_ping() || msg.is_pong() => {}
                    Some(Ok(_)) => log::warn!("V2: non-text message received"),
                    Some(Err(e)) => {
                        log::error!("V2 WebSocket error: {:?}", e);
                        break;
                    }
                    None => break,
                }
            }
        }
    }

    // The engine only exposes cancel-all; this stops playback globally.
    log_err!(map.send_event(InputEventMessage::CancelEvents));
    log::info!("V2 connection closed");
    Ok(())
}

fn parse_query_params(uri: &str) -> (String, String) {
    let mut app_id = String::new();
    let mut app_name = String::new();

    if let Some(query) = uri.split('?').nth(1) {
        for pair in query.split('&') {
            let mut kv = pair.splitn(2, '=');
            match (kv.next(), kv.next()) {
                (Some("app_id"), Some(v)) => {
                    app_id = urlencoding::decode(v).unwrap_or_default().into_owned()
                }
                (Some("app_name"), Some(v)) => {
                    app_name = urlencoding::decode(v).unwrap_or_default().into_owned()
                }
                _ => {}
            }
        }
    }

    (app_id, app_name)
}

// ─── Request handling ────────────────────────────────────────────────

async fn handle_player_request(
    raw: &str,
    state: &mut ConnectionState,
    map: &MapHandle,
    ws_tx: &mpsc::UnboundedSender<Message>,
) {
    let request: PlayerRequest = match serde_json::from_str(raw) {
        Ok(r) => r,
        Err(e) => {
            log::error!("V2 decode error: {} | raw: {:?}", e, raw);
            return;
        }
    };

    for reg in request.register {
        log::trace!("V2: Registered pattern: {}", reg.key);
        state.registered.insert(reg.key, reg.project);
    }

    for submit in request.submit {
        match submit.submit_type.as_str() {
            "key" => handle_submit_key(&submit, state, map).await,
            "frame" => handle_submit_frame(&submit, state, map).await,
            "turnOff" => handle_turn_off(&submit.key, state, map).await,
            "turnOffAll" => handle_turn_off_all(state, map).await,
            other => log::warn!("V2: Unknown submit type: {}", other),
        }
    }

    let response = build_response(state);
    if let Ok(json) = serde_json::to_string(&response) {
        let _ = ws_tx.send(Message::text(json));
    }
}

/// Registers each event and immediately starts it (the V3 `handle_auth` loop,
/// with the play step folded in). `send_event` is fire-and-forget, per V3;
/// only the registration reply is awaited.
async fn register_and_start(
    map: &MapHandle,
    state: &mut ConnectionState,
    submit_key: &str,
    events: Vec<Event>,
) {
    if events.is_empty() {
        return;
    }

    let mut started = false;
    for event in events {
        let (tx, rx) = oneshot::channel();
        log_err!(map.send_event(InputEventMessage::RegisterEvent {
            event: Box::new(event),
            reply: tx,
        }));
        match rx.await {
            Ok(key) => {
                log_err!(map.send_event(InputEventMessage::StartEvent(key)));
                started = true;
            }
            Err(e) => log::error!("V2: event register failed: {e:?}"),
        }
    }

    if started && !state.active_keys.iter().any(|k| k == submit_key) {
        state.active_keys.push(submit_key.to_string());
    }
}

// ─── Submit: key (registered pattern) ────────────────────────────────

async fn handle_submit_key(
    submit: &SubmitRequest,
    state: &mut ConnectionState,
    map: &MapHandle,
) {
    let Some(project_json) = state.registered.get(&submit.key).cloned() else {
        log::warn!("V2: Unregistered key: {}", submit.key);
        return;
    };

    let scale = extract_scale_option(&submit.parameters);
    let rotation = extract_rotation_option(&submit.parameters);

    let events = project_to_events(&project_json, &submit.key, scale, rotation);
    register_and_start(map, state, &submit.key, events).await;
}

fn extract_scale_option(params: &Option<serde_json::Value>) -> ScaleOption {
    let Some(params) = params else {
        return ScaleOption::default();
    };
    ScaleOption {
        intensity: params
            .get("scaleOption")
            .and_then(|s| s.get("intensity"))
            .and_then(|v| v.as_f64())
            .unwrap_or(1.0) as f32,
        duration: params
            .get("scaleOption")
            .and_then(|s| s.get("duration"))
            .and_then(|v| v.as_f64())
            .unwrap_or(1.0) as f32,
    }
}

fn extract_rotation_option(params: &Option<serde_json::Value>) -> RotationOption {
    let Some(params) = params else {
        return RotationOption::default();
    };
    RotationOption {
        offset_angle_x: params
            .get("rotationOption")
            .and_then(|s| s.get("offsetAngleX"))
            .and_then(|v| v.as_f64())
            .unwrap_or(0.0) as f32,
        offset_y: params
            .get("rotationOption")
            .and_then(|s| s.get("offsetY"))
            .and_then(|v| v.as_f64())
            .unwrap_or(0.0) as f32,
    }
}

#[derive(Debug, Clone)]
struct ScaleOption {
    intensity: f32,
    duration: f32,
}

impl Default for ScaleOption {
    fn default() -> Self {
        Self {
            intensity: 1.0,
            duration: 1.0,
        }
    }
}

#[derive(Debug, Clone, Default)]
struct RotationOption {
    offset_angle_x: f32,
    offset_y: f32,
}

// ─── Steps / Event construction (new model) ──────────────────────────

/// Resamples time-stamped `(time_ms, value)` samples onto a per-tick grid
/// (one tick per 10 ms) of length `ticks`, using linear interpolation.
/// Samples need not be pre-sorted. Before the first / after the last sample
/// the series is clamped to the endpoint value.
fn resample<T: Copy>(
    mut samples: Vec<(f32, T)>,
    ticks: u64,
    lerp: impl Fn(T, T, f32) -> T,
) -> Vec<T> {
    samples.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));

    let n = ticks.max(1) as usize;
    let mut out = Vec::with_capacity(n);
    if samples.is_empty() {
        return out;
    }

    let last = samples.len() - 1;
    for i in 0..n {
        let t = i as f32 * MS_PER_TICK as f32;
        if t <= samples[0].0 {
            out.push(samples[0].1);
            continue;
        }
        if t >= samples[last].0 {
            out.push(samples[last].1);
            continue;
        }
        let mut j = 1;
        while j < samples.len() && samples[j].0 < t {
            j += 1;
        }
        let (t0, v0) = samples[j - 1];
        let (t1, v1) = samples[j];
        let f = if (t1 - t0).abs() < f32::EPSILON {
            0.0
        } else {
            (t - t0) / (t1 - t0)
        };
        out.push(lerp(v0, v1, f));
    }
    out
}

/// Collapses an `f32` series to a `Const` if flat, else keeps it as `Var`.
fn value_maybe_const(values: &[f32]) -> MaybeConst<f32> {
    match values.first() {
        Some(&first) if values.iter().all(|&x| (x - first).abs() <= EPSILON) => {
            MaybeConst::new_const(first)
        }
        Some(_) => MaybeConst::Var(Arc::from(values)),
        None => MaybeConst::new_const(0.0),
    }
}

/// Collapses a `Vec3` series to a `Const` if flat, else keeps it as `Var`.
fn position_maybe_const(positions: &[Vec3]) -> MaybeConst<Vec3> {
    match positions.first() {
        Some(&first) if positions.iter().all(|p| p.distance_squared(first) <= EPSILON * EPSILON) => {
            MaybeConst::new_const(first)
        }
        Some(_) => MaybeConst::Var(Arc::from(positions)),
        None => MaybeConst::new_const(Vec3::ZERO),
    }
}

/// Builds one node from a position series and a value series (either may be a
/// single-element slice for the constant case).
fn build_node(positions: &[Vec3], values: &[f32]) -> Steps {
    Steps {
        position: position_maybe_const(positions),
        muted: MaybeConst::new_const(false),
        value: value_maybe_const(values),
        weight: MaybeConst::Const(WEIGHT),
        radius: MaybeConst::Const(RADIUS),
    }
}

/// Builds an `Event` from a set of motor nodes sharing one duration (ticks).
fn make_event(name: String, nodes: Vec<Steps>, duration_ticks: u64) -> Option<Event> {
    if nodes.is_empty() {
        return None;
    }
    match Event::new(name.clone(), Frames::new(nodes), duration_ticks) {
        Ok(event) => Some(event),
        Err(e) => {
            log::trace!("V2: event creation failed for {name}: {e:?}");
            None
        }
    }
}

// ─── Project → Events conversion ────────────────────────────────────

fn project_to_events(
    project_json: &serde_json::Value,
    key: &str,
    scale: ScaleOption,
    rotation: RotationOption,
) -> Vec<Event> {
    let mut events = Vec::new();

    let Some(tracks) = project_json.get("tracks").and_then(|t| t.as_array()) else {
        return events;
    };

    for (track_idx, track) in tracks.iter().enumerate() {
        let enabled = track.get("enable").and_then(|e| e.as_bool()).unwrap_or(true);
        if !enabled {
            continue;
        }

        let Some(effects) = track.get("effects").and_then(|e| e.as_array()) else {
            continue;
        };

        for (effect_idx, effect) in effects.iter().enumerate() {
            let start_time = effect
                .get("startTime")
                .and_then(|v| v.as_i64())
                .unwrap_or(0) as i32;
            let offset_time = effect
                .get("offsetTime")
                .and_then(|v| v.as_i64())
                .unwrap_or(0) as i32;

            let Some(modes) = effect.get("modes") else {
                continue;
            };
            let Some(modes_obj) = modes.as_object() else {
                continue;
            };

            for (position_str, mode) in modes_obj {
                let Some(location) = position_str_to_pattern(position_str) else {
                    log::trace!("V2: Skipping unknown position '{}' in project", position_str);
                    continue;
                };

                let mode_type = mode
                    .get("mode")
                    .and_then(|m| m.as_str())
                    .unwrap_or("dotMode");

                match mode_type {
                    "dotMode" | "DOT_MODE" => {
                        if let Some(dot_mode) = mode.get("dotMode") {
                            let new = dot_mode_to_events(
                                dot_mode,
                                &location,
                                key,
                                track_idx,
                                effect_idx,
                                &scale,
                            );
                            events.extend(new);
                        }
                    }
                    "pathMode" | "PATH_MODE" => {
                        if let Some(path_mode) = mode.get("pathMode") {
                            let new = path_mode_to_events(
                                path_mode,
                                &location,
                                key,
                                track_idx,
                                effect_idx,
                                start_time,
                                offset_time,
                                &scale,
                                &rotation,
                            );
                            events.extend(new);
                        }
                    }
                    other => log::trace!("V2: Unknown mode type '{}'", other),
                }
            }
        }
    }

    events
}

fn dot_mode_to_events(
    dot_mode: &serde_json::Value,
    location: &PatternLocation,
    key: &str,
    track_idx: usize,
    effect_idx: usize,
    scale: &ScaleOption,
) -> Vec<Event> {
    let mut events = Vec::new();

    let Some(feedbacks) = dot_mode.get("feedback").and_then(|f| f.as_array()) else {
        return events;
    };

    let motor_count = location.motor_count();

    for (fb_idx, feedback) in feedbacks.iter().enumerate() {
        let fb_start = feedback
            .get("startTime")
            .and_then(|v| v.as_i64())
            .unwrap_or(0) as i32;
        let fb_end = feedback
            .get("endTime")
            .and_then(|v| v.as_i64())
            .unwrap_or(0) as i32;

        let duration_ms = ((fb_end - fb_start).max(10) as f32 * scale.duration) as u64;
        let ticks = ms_to_ticks(duration_ms);

        let Some(point_list) = feedback.get("pointList").and_then(|p| p.as_array()) else {
            continue;
        };

        // Group points by motor index → time-stamped intensity samples.
        let mut motor_points: HashMap<usize, Vec<(f32, f32)>> = HashMap::new();
        for point in point_list {
            let index = point.get("index").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
            let intensity = point.get("intensity").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
            let time = point.get("time").and_then(|v| v.as_i64()).unwrap_or(0) as i32;

            let scaled_time = (time - fb_start) as f32 * scale.duration;
            let value = (intensity * scale.intensity).clamp(0.0, 1.0);
            motor_points.entry(index).or_default().push((scaled_time, value));
        }

        // One event per feedback; one node per targeted motor, resampled to ticks.
        let mut nodes = Vec::new();
        for (motor_idx, samples) in motor_points {
            if motor_idx >= motor_count || samples.is_empty() {
                continue;
            }
            let position = location.to_position(motor_idx);
            let values = resample(samples, ticks, |a, b, f| a + (b - a) * f);
            nodes.push(build_node(&[position], &values));
        }

        let name = format!("v2_{}_t{}_e{}_fb{}", key, track_idx, effect_idx, fb_idx);
        if let Some(event) = make_event(name, nodes, ticks) {
            events.push(event);
        }
    }

    events
}

fn path_mode_to_events(
    path_mode: &serde_json::Value,
    location: &PatternLocation,
    key: &str,
    track_idx: usize,
    effect_idx: usize,
    _start_time: i32,
    _offset_time: i32,
    scale: &ScaleOption,
    rotation: &RotationOption,
) -> Vec<Event> {
    let mut events = Vec::new();

    let Some(feedbacks) = path_mode.get("feedback").and_then(|f| f.as_array()) else {
        return events;
    };

    for (fb_idx, feedback) in feedbacks.iter().enumerate() {
        let Some(point_list) = feedback.get("pointList").and_then(|p| p.as_array()) else {
            continue;
        };
        if point_list.is_empty() {
            continue;
        }

        let mut path_entries: Vec<PathEntry> = Vec::new();
        for point in point_list {
            let x = point.get("x").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
            let y = point.get("y").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
            let intensity = point.get("intensity").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
            let time = point.get("time").and_then(|v| v.as_i64()).unwrap_or(0) as i32;

            // Apply rotation offset: shift x by angle, clamp y to [0,1].
            let rotated_x = (x + rotation.offset_angle_x / 360.0).rem_euclid(1.0);
            let shifted_y = (y + rotation.offset_y).clamp(0.0, 1.0);

            path_entries.push(PathEntry {
                x: rotated_x,
                y: shifted_y,
                intensity,
                time,
            });
        }

        path_entries.sort_by_key(|e| e.time);

        let time_min = path_entries.first().map(|e| e.time).unwrap_or(0);
        let time_max = path_entries.last().map(|e| e.time).unwrap_or(0);
        let duration_ms = ((time_max - time_min).max(10) as f32 * scale.duration) as u64;
        let ticks = ms_to_ticks(duration_ms);

        // Time-stamped position and intensity samples, resampled to the tick grid.
        let pos_samples: Vec<(f32, Vec3)> = path_entries
            .iter()
            .map(|e| {
                let t = (e.time - time_min) as f32 * scale.duration;
                (t, xy_to_vec3(location, e.x, e.y))
            })
            .collect();
        let val_samples: Vec<(f32, f32)> = path_entries
            .iter()
            .map(|e| {
                let t = (e.time - time_min) as f32 * scale.duration;
                (t, (e.intensity * scale.intensity).clamp(0.0, 1.0))
            })
            .collect();

        let positions = resample(pos_samples, ticks, |a, b, f| a.lerp(b, f));
        let values = resample(val_samples, ticks, |a, b, f| a + (b - a) * f);

        let name = format!("v2_{}_t{}_e{}_pfb{}", key, track_idx, effect_idx, fb_idx);
        if let Some(event) = make_event(name, vec![build_node(&positions, &values)], ticks) {
            events.push(event);
        }
    }

    events
}

struct PathEntry {
    x: f32,
    y: f32,
    intensity: f32,
    time: i32,
}

/// Converts a normalized (x, y) surface coordinate into a Vec3 world position
/// by inverse-distance weighting against the device's motor grid.
fn xy_to_vec3(location: &PatternLocation, x: f32, y: f32) -> Vec3 {
    let count = location.motor_count();
    if count == 0 {
        return Vec3::ZERO;
    }

    let mut total_weight = 0.0f32;
    let mut weighted_pos = Vec3::ZERO;

    for i in 0..count {
        let motor_pos = location.to_position(i);
        let (mx, my) = motor_index_to_xy(location, i);

        let dx = x - mx;
        let dy = y - my;
        let dist_sq = dx * dx + dy * dy;

        if dist_sq < 1e-6 {
            return motor_pos;
        }

        let weight = 1.0 / dist_sq;
        weighted_pos.x += motor_pos.x * weight;
        weighted_pos.y += motor_pos.y * weight;
        weighted_pos.z += motor_pos.z * weight;
        total_weight += weight;
    }

    if total_weight > 0.0 {
        weighted_pos.x /= total_weight;
        weighted_pos.y /= total_weight;
        weighted_pos.z /= total_weight;
    }

    weighted_pos
}

/// Maps a motor index to a normalized (x, y) coordinate on the device surface.
fn motor_index_to_xy(location: &PatternLocation, index: usize) -> (f32, f32) {
    let (cols, rows) = grid_dimensions(location);

    let col = index % cols;
    let row = index / cols;

    let x = if cols <= 1 {
        0.5
    } else {
        col as f32 / (cols - 1) as f32
    };

    let y = if rows <= 1 {
        0.5
    } else {
        row as f32 / (rows - 1) as f32
    };

    (x, y)
}

/// Returns (columns, rows) for each device type's motor grid.
fn grid_dimensions(location: &PatternLocation) -> (usize, usize) {
    match location {
        PatternLocation::VestFront | PatternLocation::VestBack => (4, 5),
        PatternLocation::ForearmL | PatternLocation::ForearmR => (3, 2),
        PatternLocation::Head => (6, 1),
        PatternLocation::HandL | PatternLocation::HandR => (3, 2),
        PatternLocation::FootL | PatternLocation::FootR => (3, 1),
        _ => (1, 1),
    }
}

// ─── Submit: frame (direct motor control) ────────────────────────────

async fn handle_submit_frame(
    submit: &SubmitRequest,
    state: &mut ConnectionState,
    map: &MapHandle,
) {
    let Some(ref frame) = submit.frame else {
        log::warn!("V2: Frame submit with no frame data");
        return;
    };

    let Some(location) = position_str_to_pattern(&frame.position) else {
        log::warn!("V2: Unknown position: {}", frame.position);
        return;
    };

    let ticks = ms_to_ticks(frame.duration_millis.max(10) as u64);
    let motor_count = location.motor_count();
    let mut nodes = Vec::new();

    for dot in &frame.dot_points {
        if dot.index >= motor_count {
            continue;
        }
        let position = location.to_position(dot.index);
        let intensity = (dot.intensity as f32).clamp(0.0, 1.0);
        nodes.push(build_node(&[position], &[intensity]));
    }

    for path in &frame.path_points {
        let pos = xy_to_vec3(&location, path.x, path.y);
        let intensity = (path.intensity as f32).clamp(0.0, 1.0);
        nodes.push(build_node(&[pos], &[intensity]));
    }

    let name = format!("v2_frame_{}", submit.key);
    let events = make_event(name, nodes, ticks).into_iter().collect();
    register_and_start(map, state, &submit.key, events).await;
}

// ─── Turn off ────────────────────────────────────────────────────────

async fn handle_turn_off(key: &str, state: &mut ConnectionState, map: &MapHandle) {
    // The engine only supports cancel-all (no per-event/per-key stop), so a
    // single-key turnOff necessarily cancels every active V2 event.
    log::warn!(
        "V2: turnOff('{}') — engine lacks per-key cancel; cancelling all events",
        key
    );
    log_err!(map.send_event(InputEventMessage::CancelEvents));
    state.active_keys.clear();
}

async fn handle_turn_off_all(state: &mut ConnectionState, map: &MapHandle) {
    log_err!(map.send_event(InputEventMessage::CancelEvents));
    state.active_keys.clear();
}

// ─── Response ────────────────────────────────────────────────────────

fn build_response(state: &ConnectionState) -> PlayerResponse {
    let connected: Vec<String> = PatternLocation::iter()
        .filter_map(pattern_to_position_str)
        .collect();

    PlayerResponse {
        registered_keys: state.registered.keys().cloned().collect(),
        active_keys: state.active_keys.clone(),
        connected_device_count: connected.len() as i32,
        connected_positions: connected,
        status: HashMap::new(),
    }
}

// ─── Position mapping ────────────────────────────────────────────────

fn position_str_to_pattern(pos: &str) -> Option<PatternLocation> {
    match pos {
        "VestFront" => Some(PatternLocation::VestFront),
        "VestBack" => Some(PatternLocation::VestBack),
        "Vest" => Some(PatternLocation::VestFront),
        "ForearmL" => Some(PatternLocation::ForearmL),
        "ForearmR" => Some(PatternLocation::ForearmR),
        "HandL" | "GloveLeft" => Some(PatternLocation::HandL),
        "HandR" | "GloveRight" => Some(PatternLocation::HandR),
        "FootL" => Some(PatternLocation::FootL),
        "FootR" => Some(PatternLocation::FootR),
        "Head" => Some(PatternLocation::Head),
        _ => None,
    }
}

fn pattern_to_position_str(loc: PatternLocation) -> Option<String> {
    let s = match loc {
        PatternLocation::VestFront => "VestFront",
        PatternLocation::VestBack => "VestBack",
        PatternLocation::ForearmL => "ForearmL",
        PatternLocation::ForearmR => "ForearmR",
        PatternLocation::HandL => "GloveLeft",
        PatternLocation::HandR => "GloveRight",
        PatternLocation::FootL => "FootL",
        PatternLocation::FootR => "FootR",
        PatternLocation::Head => "Head",
        _ => return None,
    };
    Some(s.to_string())
}

// ─── Protocol types ──────────────────────────────────────────────────

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
struct PlayerRequest {
    #[serde(default)]
    register: Vec<RegisterRequest>,
    #[serde(default)]
    submit: Vec<SubmitRequest>,
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "PascalCase")]
struct RegisterRequest {
    key: String,
    project: serde_json::Value,
}

#[derive(Debug, serde::Deserialize)]
struct SubmitRequest {
    #[serde(rename = "type")]
    submit_type: String,
    #[serde(default)]
    key: String,
    #[serde(rename = "Parameters")]
    parameters: Option<serde_json::Value>,
    #[serde(rename = "Frame")]
    frame: Option<Frame>,
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct Frame {
    duration_millis: u32,
    position: String,
    #[serde(default)]
    path_points: Vec<PathPoint>,
    #[serde(default)]
    dot_points: Vec<DotPoint>,
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct DotPoint {
    index: usize,
    intensity: i32,
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct PathPoint {
    x: f32,
    y: f32,
    intensity: i32,
    #[serde(default = "default_motor_count")]
    motor_count: i32,
}

fn default_motor_count() -> i32 {
    3
}

#[derive(Debug, serde::Serialize)]
#[serde(rename_all = "PascalCase")]
struct PlayerResponse {
    registered_keys: Vec<String>,
    active_keys: Vec<String>,
    connected_device_count: i32,
    connected_positions: Vec<String>,
    status: HashMap<String, Vec<i32>>,
}