// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDeviceList: () => __TAURI_INVOKE<([DeviceId, DeviceInfo | null])[]>("get_device_list"),
	getVrcInfo: () => __TAURI_INVOKE<VrcInfo>("get_vrc_info"),
	// Gets the core haptics map that is used to drive feedback.
	getCoreMap: () => __TAURI_INVOKE<MapInfo>("get_core_map"),
	// sets all vrc relevant info. It is all behind an arcswap so it is the same cost to set all or one of them.
	setVrc: (mult: number, ratio: number, samples: number, smoothS: {
	secs: number,
	nanos: number,
}) => __TAURI_INVOKE<void>("set_vrc", { mult, ratio, samples, smoothS }),
	// handles persisting and splitting out individual states to where they need to go.
	setDeviceInfo: (id: DeviceId, inf: DeviceInfo) => __TAURI_INVOKE<void>("set_device_info", { id, inf }),
	getRepositories: () => __TAURI_INVOKE<GitRepo[]>("get_repositories"),
	setRepositories: (repos: GitRepo[]) => __TAURI_INVOKE<void>("set_repositories", { repos }),
	getWifiTimeout: () => __TAURI_INVOKE<number>("get_wifi_timeout"),
	setWifiTimeout: (timeout: number) => __TAURI_INVOKE<void>("set_wifi_timeout", { timeout }),
	uploadDeviceMap: (id: string, configJson: string) => typedError<null, string>(__TAURI_INVOKE("upload_device_map", { id, configJson })),
	updateDeviceMultiplier: (deviceId: DeviceId, multiplier: number) => __TAURI_INVOKE<void>("update_device_multiplier", { deviceId, multiplier }),
	updateDeviceOffset: (deviceId: DeviceId, offset: number) => __TAURI_INVOKE<void>("update_device_offset", { deviceId, offset }),
	// Handles resetting bhaptics to be the default player
	bhapticsLaunchDefault: () => __TAURI_INVOKE<void>("bhaptics_launch_default"),
	// Handles setting our app to launch instead of the bHapticsPlayer
	bhapticsLaunchVrch: () => __TAURI_INVOKE<void>("bhaptics_launch_vrch"),
	// Plays the specified point for the duration in seconds at the power percentage of intensity.
	playPoint: (feedbackLocation: [number, number, number], power: number, duration: number) => typedError<null, null>(__TAURI_INVOKE("play_point", { feedbackLocation, power, duration })),
	// Swaps the haptic node indices on the given device id
	swapConfNodes: (deviceId: string, pos1: Vec3, pos2: Vec3) => typedError<null, string>(__TAURI_INVOKE("swap_conf_nodes", { deviceId, pos1, pos2 })),
	setTagsRadius: (tag: string, radius: number) => typedError<null, null>(__TAURI_INVOKE("set_tags_radius", { tag, radius })),
	setNodeRadius: (id: string, radius: number) => typedError<null, string>(__TAURI_INVOKE("set_node_radius", { id, radius })),
	getDeviceEspModel: (id: string) => typedError<ESP32Model, string>(__TAURI_INVOKE("get_device_esp_model", { id })),
	// typescript seems to throw a fit with formats here. So invoke bypasses most of this. EUUUGH
	startDeviceUpdate: (fw: Firmware) => typedError<null, string>(__TAURI_INVOKE("start_device_update", { fw })),
};

/* Types */
/**
 *  Abstraction over raw VRC parameters.
 * 
 *  Represents all relevant *Descriptive* data. Does not contain any relevant high-speed or low latency datat.
 */
export type Avatar = {
	// The avatar reffered to by the VRC api
	id: string,
	// the names of the prefabs from the avatar parameter
	prefab_names: string[],
	// All information mapping OSC Parameters to their needed formats
	configs: GameMap[],
};

export type BhapticInfo = {
	id: DeviceId,
	nodes: HapticNode[],
	model: BhapticsModel,
};

export type BhapticsModel = "TacsuitX16";

/**
 *  A node cached by vrc, is an intermdieary between an `InputNode`.
 *  
 *  Provides simple methods for extracting values
 */
export type CacheNode = {
	/**
	 *  Ring buffer of values we have recieved.
	 *  Front items are the most recent.
	 */
	values: ([SpectaOscType, {
	duration_since_epoch: number,
	duration_since_unix_epoch: number,
}])[],
	// Keep track of ray's seperately
	ray_values: ([SpectaOscType, {
	duration_since_epoch: number,
	duration_since_unix_epoch: number,
}])[],
	/**
	 *  contains the OscType that this CacheNode accepts.
	 *  The payload should be considered the default value if the cache is empty.
	 */
	osc_type: SpectaOscType,
	// the max_len of entries we will keep track of.
	max_len: number,
	// The state of haptics returned from this node.
	smoothing_time: {
		secs: number,
		nanos: number,
	},
};

// Metadata from the json config
export type ConfMetadata = {
	map_name: string,
	map_version: number,
	map_author: string,
};

/**
 *  Haptic Node information from the game config
 *  Contains more information than the default HapticNode to help with locating
 */
export type ConfNode = {
	node_data: HapticNode,
	address: string,
	is_external_address: boolean,
	radius: number,
	target_bone: TargetBone,
	ray?: RayNode | null,
};

export type DeviceId = string;

/**
 *  Info container for each device type
 *  
 *  An informattion that should be in all variants should be made so via the below impl.
 *  Don't manually dip into each variant please.
 */
export type DeviceInfo = { variant: "Wifi"; value: WifiDeviceInfo } | { variant: "BhapticBle"; value: BhapticInfo };

// The firmware type returned from the device.
export type ESP32Model = 
// All original ESP32 variants
"ESP32" | 
// Standard ESP32-S2
"ESP32S2" | 
// ESP32-S2 with 16MB flash
"ESP32S2FH16" | 
// ESP32-S2 with 32MB flash  
"ESP32S2FH32" | "ESP32S3" | "ESP32C3" | "ESP32C2" | "ESP32C6" | "ESP8266" | "Unknown";

/**
 *  Represents a haptic event that takes place over time.
 *  
 *  Depends on `EventEffectType`
 */
export type Event = {
	// user facing name
	name: string,
	// how should this event effect the input map
	effect: EventEffectType,
	// The different outputs that should be output at different times.
	steps: number[],
	/**
	 *  The total duration of this event.
	 * 
	 *  Steps will be distributed across this duration.
	 */
	duration: {
		secs: number,
		nanos: number,
	},
	// Tags that will be inserted to each node created by this event.
	tags: string[],
	// radius of effect this event will have
	radius: number,
	managed_nodes: NodeId[],
	time_step: {
		secs: number,
		nanos: number,
	},
	steps_completed: number,
	start_time: {
	duration_since_epoch: number,
	duration_since_unix_epoch: number,
} | null,
};

// Describes what effect an event should have.
export type EventEffectType = 
/**
 *  Will try to set this node id to this value,
 *  Does not remove node after finished.
 */
({ SingleNode: NodeId }) & { Location?: never; MovingLocation?: never; MultipleNodes?: never; Tags?: never } | 
// Same as single node, but with a list of them.
({ MultipleNodes: NodeId[] }) & { Location?: never; MovingLocation?: never; SingleNode?: never; Tags?: never } | 
// Effects all InputNodes with the given tag.
({ Tags: string[] }) & { Location?: never; MovingLocation?: never; MultipleNodes?: never; SingleNode?: never } | 
// Inserts a node at the given location, automatically removes node when event expires.
({ Location: Vec3 }) & { MovingLocation?: never; MultipleNodes?: never; SingleNode?: never; Tags?: never } | 
// Divides locations between the duration of the event and moves the node to that location.
({ MovingLocation: Vec3[] }) & { Location?: never; MultipleNodes?: never; SingleNode?: never; Tags?: never };

// Bundle containing all user-required information to start a firmware update.
export type Firmware = {
	// The ID that should be used to find the device:
	id: string,
	// The method used to update firmware.
	method: UpdateMethod,
	// Raw bytes of the .bin fw file.
	bytes: number[],
};

/**
 *  Filled with values from a config json file.
 *  Provides all information needed to fully define the avatar prefab.
 */
export type GameMap = {
	nodes: ConfNode[],
	meta: ConfMetadata,
};

export type GitRepo = {
	owner: string,
	name: string,
};

/**
 *  Struct defining all needed properties for a haptic node.
 *  Used for mapping from one haptic model to another.
 *  Units are in Meters: Y is vertical, X is aligned with the Right Arm, Z is towards the front.
 *  Standard location is zeroed at the reference models feet, directly below the viewpoint.
 */
export type HapticNode = {
	// Standard Location in x (meters)
	x: number,
	// Standard Location in y (meters)
	y: number,
	// Standard Location in z (meters)
	z: number,
	// The NodeGroups this node should influence or take influence from
	groups: NodeGroup[],
};

// All information needed to compute an OuputNode of any given location
export type InputNode = {
	// id Unique to this InputNode
	id: NodeId,
	// Contains the standard location and NodeGroup tags for calculating outputs
	haptic_node: HapticNode,
	// The feedback strength at this location
	intensity: number,
	// The radius that this node will impact
	radius: number,
	// used to identify/modify/remove groups of InputNodes. (tags are not NodeGroups)  
	tags: string[],
	// how this input node should be interpreted
	input_type: InputType,
};

/**
 *  Describes how an `InputNode` should be used during interpolation.
 * 
 *  Layers are ordered in processing order according to the enum, with the cumulative outputs being passed to the next step.
 */
export type InputType = 
/**
 *  Default choice, which weights closer values exponentially more.
 * 
 *  Output will not be influenced easily by distant input nodes if there is one close to the output node.
 */
"INTERP" | 
/**
 *  Additive layers adds the nodes influence into the result of the `InputType::INTERP` step.
 * 
 *  Uses linear scaling based off of the `InputNode.radius`
 */
"ADDITIVE" | 
/**
 *  Subtractive layers subtracts the nodes influence into the result of the `InputType::INTERP` step.
 * 
 *  Uses linear scaling based off of the `InputNode.radius`
 */
"SUBTRACTIVE";

// Snapshot of map state.
export type MapInfo = {
	nodes: InputNode[],
	events: Event[],
};

/**
 *  Descriptors for location groups.
 *  Allows for segmented Interpolation
 */
export type NodeGroup = "Head" | "UpperArmRight" | "UpperArmLeft" | "LowerArmRight" | "LowerArmLeft" | "TorsoRight" | "TorsoLeft" | "TorsoFront" | "TorsoBack" | "UpperLegRight" | "UpperLegLeft" | "LowerLegRight" | "LowerLegLeft" | "FootRight" | "FootLeft" | 
/**
 *  A meta tag reserved for in-server use only.
 *  Should not be exported to devices or imported from games.
 */
"All";

/**
 *  Id unique to the node it references.
 *  if an Id is equal, it is garunteed to be the same HapticNode, with location in space and tags
 */
export type NodeId = string;

export type OscAccessLevel = "Refused" | "OnlyRead" | "OnlyWrite" | "Full";

export type OscInfo = {
	full_path: OscPath,
	access: OscAccessLevel,
	value: SpectaOscType[],
	description: string | null,
};

/**
 *  Simple wrapper for the String class.
 *  Represnts a full OscPath without any elements stripped,
 *  other than the VRC Fury naming.
 */
export type OscPath = string;

export type OtaPassword = string;

export type RayNode = {
	rotation_offset: Vec3,
	position_offset: Vec3,
	size: number,
};

export type SpectaOscType = ({ Int: number }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Float: number }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ String: string }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; Time?: never } | ({ Long: number }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Midi?: never; String?: never; Time?: never } | ({ Double: number }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Char: string }) & { Array?: never; Blob?: never; Bool?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Bool: boolean }) & { Array?: never; Blob?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | "Nil" | "Inf" | ({ Blob: number[] }) & { Array?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Time: {
	seconds: number,
	fractional: number,
} }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never } | ({ Color: {
	r: number,
	g: number,
	b: number,
	a: number,
} }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Midi: {
	port: number,
	status: number,
	data1: number,
	data2: number,
} }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; String?: never; Time?: never } | ({ Array: SpectaOscType[] }) & { Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never };

/**
 *  The bone that the node is parented to in the prefab.
 *  (HumanBodyBones from Unity,)
 */
export type TargetBone = 
/**
 *  <summary>
 *    <para>This is the Hips bone.</para>
 *  </summary>
 */
"Hips" | 
/**
 *  <summary>
 *    <para>This is the Left Upper Leg bone.</para>
 *  </summary>
 */
"LeftUpperLeg" | 
/**
 *  <summary>
 *    <para>This is the Right Upper Leg bone.</para>
 *  </summary>
 */
"RightUpperLeg" | 
/**
 *  <summary>
 *    <para>This is the Left Knee bone.</para>
 *  </summary>
 */
"LeftLowerLeg" | 
/**
 *  <summary>
 *    <para>This is the Right Knee bone.</para>
 *  </summary>
 */
"RightLowerLeg" | 
/**
 *  <summary>
 *    <para>This is the Left Ankle bone.</para>
 *  </summary>
 */
"LeftFoot" | 
/**
 *  <summary>
 *    <para>This is the Right Ankle bone.</para>
 *  </summary>
 */
"RightFoot" | 
/**
 *  <summary>
 *    <para>This is the first Spine bone.</para>
 *  </summary>
 */
"Spine" | 
/**
 *  <summary>
 *    <para>This is the Chest bone.</para>
 *  </summary>
 */
"Chest" | 
/**
 *  <summary>
 *    <para>This is the Neck bone.</para>
 *  </summary>
 */
"Neck" | 
/**
 *  <summary>
 *    <para>This is the Head bone.</para>
 *  </summary>
 */
"Head" | 
/**
 *  <summary>
 *    <para>This is the Left Shoulder bone.</para>
 *  </summary>
 */
"LeftShoulder" | 
/**
 *  <summary>
 *    <para>This is the Right Shoulder bone.</para>
 *  </summary>
 */
"RightShoulder" | 
/**
 *  <summary>
 *    <para>This is the Left Upper Arm bone.</para>
 *  </summary>
 */
"LeftUpperArm" | 
/**
 *  <summary>
 *    <para>This is the Right Upper Arm bone.</para>
 *  </summary>
 */
"RightUpperArm" | 
/**
 *  <summary>
 *    <para>This is the Left Elbow bone.</para>
 *  </summary>
 */
"LeftLowerArm" | 
/**
 *  <summary>
 *    <para>This is the Right Elbow bone.</para>
 *  </summary>
 */
"RightLowerArm" | 
/**
 *  <summary>
 *    <para>This is the Left Wrist bone.</para>
 *  </summary>
 */
"LeftHand" | 
/**
 *  <summary>
 *    <para>This is the Right Wrist bone.</para>
 *  </summary>
 */
"RightHand" | 
/**
 *  <summary>
 *    <para>This is the Left Toes bone.</para>
 *  </summary>
 */
"LeftToes" | 
/**
 *  <summary>
 *    <para>This is the Right Toes bone.</para>
 *  </summary>
 */
"RightToes" | 
/**
 *  <summary>
 *    <para>This is the Left Eye bone.</para>
 *  </summary>
 */
"LeftEye" | 
/**
 *  <summary>
 *    <para>This is the Right Eye bone.</para>
 *  </summary>
 */
"RightEye" | 
/**
 *  <summary>
 *    <para>This is the Jaw bone.</para>
 *  </summary>
 */
"Jaw" | 
/**
 *  <summary>
 *    <para>This is the left thumb 1st phalange.</para>
 *  </summary>
 */
"LeftThumbProximal" | 
/**
 *  <summary>
 *    <para>This is the left thumb 2nd phalange.</para>
 *  </summary>
 */
"LeftThumbIntermediate" | 
/**
 *  <summary>
 *    <para>This is the left thumb 3rd phalange.</para>
 *  </summary>
 */
"LeftThumbDistal" | 
/**
 *  <summary>
 *    <para>This is the left index 1st phalange.</para>
 *  </summary>
 */
"LeftIndexProximal" | 
/**
 *  <summary>
 *    <para>This is the left index 2nd phalange.</para>
 *  </summary>
 */
"LeftIndexIntermediate" | 
/**
 *  <summary>
 *    <para>This is the left index 3rd phalange.</para>
 *  </summary>
 */
"LeftIndexDistal" | 
/**
 *  <summary>
 *    <para>This is the left middle 1st phalange.</para>
 *  </summary>
 */
"LeftMiddleProximal" | 
/**
 *  <summary>
 *    <para>This is the left middle 2nd phalange.</para>
 *  </summary>
 */
"LeftMiddleIntermediate" | 
/**
 *  <summary>
 *    <para>This is the left middle 3rd phalange.</para>
 *  </summary>
 */
"LeftMiddleDistal" | 
/**
 *  <summary>
 *    <para>This is the left ring 1st phalange.</para>
 *  </summary>
 */
"LeftRingProximal" | 
/**
 *  <summary>
 *    <para>This is the left ring 2nd phalange.</para>
 *  </summary>
 */
"LeftRingIntermediate" | 
/**
 *  <summary>
 *    <para>This is the left ring 3rd phalange.</para>
 *  </summary>
 */
"LeftRingDistal" | 
/**
 *  <summary>
 *    <para>This is the left little 1st phalange.</para>
 *  </summary>
 */
"LeftLittleProximal" | 
/**
 *  <summary>
 *    <para>This is the left little 2nd phalange.</para>
 *  </summary>
 */
"LeftLittleIntermediate" | 
/**
 *  <summary>
 *    <para>This is the left little 3rd phalange.</para>
 *  </summary>
 */
"LeftLittleDistal" | 
/**
 *  <summary>
 *    <para>This is the right thumb 1st phalange.</para>
 *  </summary>
 */
"RightThumbProximal" | 
/**
 *  <summary>
 *    <para>This is the right thumb 2nd phalange.</para>
 *  </summary>
 */
"RightThumbIntermediate" | 
/**
 *  <summary>
 *    <para>This is the right thumb 3rd phalange.</para>
 *  </summary>
 */
"RightThumbDistal" | 
/**
 *  <summary>
 *    <para>This is the right index 1st phalange.</para>
 *  </summary>
 */
"RightIndexProximal" | 
/**
 *  <summary>
 *    <para>This is the right index 2nd phalange.</para>
 *  </summary>
 */
"RightIndexIntermediate" | 
/**
 *  <summary>
 *    <para>This is the right index 3rd phalange.</para>
 *  </summary>
 */
"RightIndexDistal" | 
/**
 *  <summary>
 *    <para>This is the right middle 1st phalange.</para>
 *  </summary>
 */
"RightMiddleProximal" | 
/**
 *  <summary>
 *    <para>This is the right middle 2nd phalange.</para>
 *  </summary>
 */
"RightMiddleIntermediate" | 
/**
 *  <summary>
 *    <para>This is the right middle 3rd phalange.</para>
 *  </summary>
 */
"RightMiddleDistal" | 
/**
 *  <summary>
 *    <para>This is the right ring 1st phalange.</para>
 *  </summary>
 */
"RightRingProximal" | 
/**
 *  <summary>
 *    <para>This is the right ring 2nd phalange.</para>
 *  </summary>
 */
"RightRingIntermediate" | 
/**
 *  <summary>
 *    <para>This is the right ring 3rd phalange.</para>
 *  </summary>
 */
"RightRingDistal" | 
/**
 *  <summary>
 *    <para>This is the right little 1st phalange.</para>
 *  </summary>
 */
"RightLittleProximal" | 
/**
 *  <summary>
 *    <para>This is the right little 2nd phalange.</para>
 *  </summary>
 */
"RightLittleIntermediate" | 
/**
 *  <summary>
 *    <para>This is the right little 3rd phalange.</para>
 *  </summary>
 */
"RightLittleDistal" | 
/**
 *  <summary>
 *    <para>This is the Upper Chest bone.</para>
 *  </summary>
 */
"UpperChest" | 
/**
 *  <summary>
 *    <para>This is the Last bone index delimiter.</para>
 *  </summary>
 */
"LastBone";

/**
 *  Which method to use.
 * 
 *  Can contain information on details that aren't automatically negotiable.
 */
export type UpdateMethod = 
// over the air updatetyp. OtaPassword; authentication password (default: `Haptics-OTA`)
({ OTA: OtaPassword }) & { Serial?: never } | 
// Not currently supported
({ Serial: string }) & { OTA?: never };

// Minimal 3‑vector with **f32** components for high‑throughput numeric geometry.
export type Vec3 = {
	x: number,
	y: number,
	z: number,
};

/**
 *  struct exposed to the UI.
 * 
 *  Seperates serializable with under the hood specifications.
 */
export type VrcInfo = {
	is_connected: boolean,
	in_port: number | null,
	out_port: number | null,
	avatar: Avatar | null,
	velocity_ratio: number,
	velocity_mult: number,
	cached: ([OscPath, CacheNode])[],
	available: OscInfo[],
};

export type WifiDeviceInfo = {
	nodes: HapticNode[],
	remote_addr: string,
	name: string,
	mac: string,
	rssi: number,
	esp_model: ESP32Model,
	offset: number,
	intensity: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

