// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDeviceList: () => __TAURI_INVOKE<([DeviceId, DeviceInfo | null])[]>("get_device_list"),
	getVrcInfo: () => typedError<VrcInfo, null>(__TAURI_INVOKE("get_vrc_info")),
	// Gets the core haptics map that is used to drive feedback.
	getCoreMap: () => typedError<Snapshot, null>(__TAURI_INVOKE("get_core_map")),
	// sets all vrc relevant info. It is all behind an arcswap so it is the same cost to set all or one of them.
	setVrc: (mult: number, ratio: number, samples: number, smoothS: {
	secs: number,
	nanos: number,
}) => __TAURI_INVOKE<void>("set_vrc", { mult, ratio, samples, smoothS }),
	// handles persisting and splitting out individual states to where they need to go.
	setDeviceInfo: (id: DeviceId, inf: DeviceInfo) => __TAURI_INVOKE<void>("set_device_info", { id, inf }),
	getRepositories: () => __TAURI_INVOKE<GitRepo[]>("get_repositories"),
	setRepositories: (repos: GitRepo[]) => __TAURI_INVOKE<void>("set_repositories", { repos }),
	getWifiTimeout: () => __TAURI_INVOKE<number>("get_wifi_timeout"),
	setWifiTimeout: (timeout: number) => __TAURI_INVOKE<void>("set_wifi_timeout", { timeout }),
	uploadDeviceMap: (id: string, configJson: string) => typedError<null, string>(__TAURI_INVOKE("upload_device_map", { id, configJson })),
	updateDeviceMultiplier: (deviceId: DeviceId, multiplier: number) => __TAURI_INVOKE<void>("update_device_multiplier", { deviceId, multiplier }),
	updateDeviceOffset: (deviceId: DeviceId, offset: number) => __TAURI_INVOKE<void>("update_device_offset", { deviceId, offset }),
	// Handles resetting bhaptics to be the default player
	bhapticsLaunchDefault: () => __TAURI_INVOKE<void>("bhaptics_launch_default"),
	// Handles setting our app to launch instead of the bHapticsPlayer
	bhapticsLaunchVrch: () => __TAURI_INVOKE<void>("bhaptics_launch_vrch"),
	// Plays the specified point for the duration in seconds at the power percentage of intensity.
	playPoint: (feedbackLocation: [number, number, number], power: number, duration: number) => typedError<null, null>(__TAURI_INVOKE("play_point", { feedbackLocation, power, duration })),
	// Swaps the haptic node indices on the given device id
	swapConfNodes: (deviceId: string, pos1: [number, number, number], pos2: [number, number, number]) => typedError<null, string>(__TAURI_INVOKE("swap_conf_nodes", { deviceId, pos1, pos2 })),
	setNodesRadius: (keys: NodeKeyDef[], radius: number) => typedError<null, null>(__TAURI_INVOKE("set_nodes_radius", { keys, radius })),
	getDeviceEspModel: (id: string) => typedError<ESP32Model, string>(__TAURI_INVOKE("get_device_esp_model", { id })),
	// typescript seems to throw a fit with formats here. So invoke bypasses most of this. EUUUGH
	startDeviceUpdate: (fw: Firmware) => typedError<null, string>(__TAURI_INVOKE("start_device_update", { fw })),
};

/* Types */
export type AddrInfo = ({ Slot: [SlotKey, SlotFieldKind] }) & { Node?: never } | ({ Node: [NodeKeyDef, NodeFieldKind] }) & { Slot?: never };

/**
 *  Abstraction over raw VRC parameters.
 * 
 *  Represents all relevant *Descriptive* data. Does not contain any relevant high-speed or low latency datat.
 */
export type Avatar = {
	// The avatar referred to by the VRC api
	id: string,
	// the names of the prefabs from the avatar parameter
	prefab_names: string[],
	// All information mapping OSC Parameters to their needed formats
	configs: GameMap[],
};

export type BhapticInfo = {
	id: DeviceId,
	nodes: HapticNode[],
	model: BhapticsModel,
};

export type BhapticsModel = "TacsuitX16";

// Metadata from the json config
export type ConfIdent = {
	mapName: string,
	mapVersion: number,
	authorName: string,
	authorId: string | null,
	customRepository: CustomRepo | null,
};

/**
 *  Haptic Node information from the game config
 *  Contains more information than the default HapticNode to help with locating
 */
export type ConfNode = {
	location: [number, number, number],
	interactionTags: NodeGroup,
	parentBone: TargetBone,
	interpolationLayer: InterpolationLayer,
	// The radius that will be used during interpolation
	radius: number,
	inputs: Input[],
};

// where to retrieve different versions of this map
export type CustomRepo = {
	author: string,
	mapName: string,
	mapAuthor: string,
};

export type DeviceId = string;

/**
 *  Info container for each device type
 *  
 *  An information that should be in all variants should be made so via the below impl.
 *  Don't manually dip into each variant please.
 */
export type DeviceInfo = { variant: "Wifi"; value: WifiDeviceInfo } | { variant: "BhapticBle"; value: BhapticInfo } | { variant: "Websocket"; value: WebsocketDeviceInfo } | { variant: "Internal"; value: InternalDeviceInfo };

// The firmware type returned from the device.
export type ESP32Model = 
// All original ESP32 variants
"ESP32" | 
// Standard ESP32-S2
"ESP32S2" | 
// ESP32-S2 with 16MB flash
"ESP32S2FH16" | 
// ESP32-S2 with 32MB flash  
"ESP32S2FH32" | "ESP32S3" | "ESP32C3" | "ESP32C2" | "ESP32C6" | "ESP8266" | "Unknown";

// Represents a haptic event that takes place over time.
export type Event = {
	// user facing name
	name: string,
	// lots of identical events can be triggered.
	frames: Frames,
	/**
	 *  The total duration of this even in event ticks (100hz)
	 *  
	 *  Nodes will be active in the map for this long and modified by the frames inserted.
	 */
	duration: number,
};

export type EventKey = number;

// Bundle containing all user-required information to start a firmware update.
export type Firmware = {
	// The ID that should be used to find the device:
	id: string,
	// The method used to update firmware.
	method: UpdateMethod,
	// Raw bytes of the .bin fw file.
	bytes: number[],
};

// A collection of values and consts, Constant values will only be initialized.
export type Frames = {
	nodes: Steps[],
};

/**
 *  Filled with values from a config json file.
 *  Provides all information needed to fully define the avatar prefab.
 */
export type GameMap = {
	schemaVersion: string,
	nodes: ConfNode[],
	identification: ConfIdent,
};

export type GitRepo = {
	owner: string,
	name: string,
};

/**
 *  Struct defining all needed properties for a haptic node.
 *  Used for mapping from one haptic model to another.
 *  Units are in Meters-ish: Y is vertical, X is aligned with the Right Arm, Z is towards the front.
 *  Standard location is zeroed at the reference models feet, directly below the viewpoint.
 */
export type HapticNode = {
	loc: [number, number, number],
	// The NodeGroups this node should influence or take influence from
	groups: NodeGroup,
};

// describes an input source.
export type Input = {
	weight: number,
	address: string,
	vrcPrefix: string,
	externalSource: boolean,
	source: InputType,
	layer: InputLayer,
	shape: InputShape,
};

/**
 *  How this input interacts within it's own sources.
 *  
 *  Gate(Max((Additive + Subtractive) * Multiplicative, Minimum of Max Layer), Maximum of Min Layer) Clamped to 0.0-1.0 (Overridden by first Override layer)
 */
export type InputLayer = 
// Additive and subtractive combine to create base cumulative values.
"additive" | "subtractive" | 
// multiplies by cumulative value
"multiplicative" | 
// Takes Either cumulative or this value, whichever is bigger
"max" | 
// Takes Either cumulative or this value, whichever is smaller
"gate" | 
// Should be use sparingly, could very much so disrupt the outputs.
"override";

/**
 *  Represents information at a point in space that will go into computing outputs.
 *  
 *  To have a Greedy layer drive multiple devices it must have the ALL group tag present. 
 */
export type InputNode = {
	muted: boolean,
	location: [number, number, number],
	// A slot is an single input value.
	slots: Slot[],
	radius: number,
	// purely for convenience, should be determined by the map.
	interpolation_layer: InterpolationLayer,
	groups: NodeGroup,
	// The most recently calculated output value of this node.
	value: number,
};

// The shape that is used in game, gives us some special ways to interpolate some shapes.
export type InputShape = { type: "sphere"; radius: number } | { type: "capsule"; radius: number; length: number; rotation: [number, number, number, number] } | { type: "ray"; len: number; offset: number };

/**
 *  Whether this input source should be interpreted as weight or velocity.
 *  Should be moved to mapping if it ends up in there.
 */
export type InputType = "weight" | "velocity";

export type InternalDeviceInfo = {
	nodes: HapticNode[],
};

// Describes how this node should affect the layers. 
export type InterpolationLayer = 
// Grabs any nodes within it's radius,forcefully drives it at this value.
"greedy" | 
// Exponentially weights nodes within it's radius, nodes at 0 pull to zero.
"default" | 
// Weights nodes according to their proximity to this node
"linear" | 
// Weights all outputs at  in its radius.
"area" | 
// Drives **all** nodes exactly at output without regard to distance.
"global";

export type MaybeConst<T> = 
/**
 *  Is not constant, an index for each frame. 
 *  Will behave like constant after running out of frames.
 */
({ Var: T[] }) & { Const?: never } | 
// Will be constant for the duration of this event.
({ Const: T }) & { Var?: never };

export type NodeFieldKind = "Muted" | "Location" | "Radius";

export type NodeGroup = number;

export type NodeKeyDef = {
	idx: number,
	version: number,
};

export type Nodes = {
	// List of event's active nodes.
	transient: { [key in number]: NodeKeyDef[] },
	nodes: (InputNode | null)[],
	active_streaming: NodeKeyDef[],
};

export type OscAccessLevel = "Refused" | "OnlyRead" | "OnlyWrite" | "Full";

export type OscInfo = {
	full_path: OscPath,
	access: OscAccessLevel,
	value: SpectaOscType[],
	description: string | null,
};

/**
 *  Simple wrapper for the String class.
 *  Represnts a full OscPath without any elements stripped,
 *  other than the VRC Fury naming.
 */
export type OscPath = string;

export type OtaPassword = string;

export type Slot = {
	muted: boolean,
	source: InputType,
	layer: InputLayer,
	weight: number,
};

export type SlotFieldKind = "Value" | "Weight" | "Muted";

// Points to an input slot, within a node, within an interpolation layer.
export type SlotKey = {
	node: NodeKeyDef,
	slot_idx: number,
};

export type Snapshot = {
	instant: number,
	active_events: ([number, EventKey, number])[],
	events: Event[],
	input_nodes: Nodes,
};

export type SpectaOscType = ({ Int: number }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Float: number }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ String: string }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; Time?: never } | ({ Long: number }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Midi?: never; String?: never; Time?: never } | ({ Double: number }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Char: string }) & { Array?: never; Blob?: never; Bool?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Bool: boolean }) & { Array?: never; Blob?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | "Nil" | "Inf" | ({ Blob: number[] }) & { Array?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Time: {
	seconds: number,
	fractional: number,
} }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never } | ({ Color: {
	r: number,
	g: number,
	b: number,
	a: number,
} }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never } | ({ Midi: {
	port: number,
	status: number,
	data1: number,
	data2: number,
} }) & { Array?: never; Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; String?: never; Time?: never } | ({ Array: SpectaOscType[] }) & { Blob?: never; Bool?: never; Char?: never; Color?: never; Double?: never; Float?: never; Int?: never; Long?: never; Midi?: never; String?: never; Time?: never };

export type Steps = {
	position: MaybeConst<[number, number, number]>,
	muted: MaybeConst<boolean>,
	value: MaybeConst<number>,
	weight: MaybeConst<number>,
	radius: MaybeConst<number>,
};

/**
 *  The bone that the node is parented to in the prefab.
 *  (HumanBodyBones from Unity,)
 */
export type TargetBone = "hips" | "leftUpperLeg" | "rightUpperLeg" | "leftLowerLeg" | "rightLowerLeg" | "leftFoot" | "rightFoot" | "spine" | "chest" | "neck" | "head" | "leftShoulder" | "rightShoulder" | "leftUpperArm" | "rightUpperArm" | "leftLowerArm" | "rightLowerArm" | "leftHand" | "rightHand" | "leftToes" | "rightToes" | "leftEye" | "rightEye" | "jaw" | "leftThumbProximal" | "leftThumbIntermediate" | "leftThumbDistal" | "leftIndexProximal" | "leftIndexIntermediate" | "leftIndexDistal" | "leftMiddleProximal" | "leftMiddleIntermediate" | "leftMiddleDistal" | "leftRingProximal" | "leftRingIntermediate" | "leftRingDistal" | "leftLittleProximal" | "leftLittleIntermediate" | "leftLittleDistal" | "rightThumbProximal" | "rightThumbIntermediate" | "rightThumbDistal" | "rightIndexProximal" | "rightIndexIntermediate" | "rightIndexDistal" | "rightMiddleProximal" | "rightMiddleIntermediate" | "rightMiddleDistal" | "rightRingProximal" | "rightRingIntermediate" | "rightRingDistal" | "rightLittleProximal" | "rightLittleIntermediate" | "rightLittleDistal" | "upperChest" | "lastBone";

/**
 *  Which method to use.
 * 
 *  Can contain information on details that aren't automatically negotiable.
 */
export type UpdateMethod = 
// over the air updatetyp. OtaPassword; authentication password (default: `Haptics-OTA`)
({ OTA: OtaPassword }) & { Serial?: never } | 
// Not currently supported
({ Serial: string }) & { OTA?: never };

/**
 *  struct exposed to the UI.
 * 
 *  Seperates serializable with under the hood specifications.
 */
export type VrcInfo = {
	is_connected: boolean,
	in_port: number | null,
	out_port: number | null,
	avatar: Avatar | null,
	velocity_ratio: number,
	velocity_mult: number,
	watched: ([string, AddrInfo])[],
	available: OscInfo[],
};

export type WebsocketDeviceInfo = {
	id: DeviceId,
	name: string,
	nodes: HapticNode[],
};

export type WifiDeviceInfo = {
	nodes: HapticNode[],
	remote_addr: string,
	name: string,
	mac: string,
	rssi: number,
	esp_model: ESP32Model,
	offset: number,
	intensity: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

