name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: '--config src-tauri/tauri.windows.conf.json'
          - platform: 'ubuntu-22.04'
            args: '--config src-tauri/tauri.linux.conf.json'
          - platform: 'ubuntu-22.04-arm'
            args: '--config src-tauri/tauri.linux.conf.json'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            build-essential \
            curl \
            wget \
            file \
            patchelf \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            clang \
            zlib1g-dev

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: ^10

      - name: Install dotnet for sidecars
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.x.x

      - name: Compile Dotnet Library
        run: |
          chmod +x ./src-vrc-oscquery/listen-for-vrc/build.sh
          ./src-vrc-oscquery/listen-for-vrc/build.sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@nightly

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Compile rust sidecars (Windows only)
        if: runner.os == 'Windows'
        run: |
          cd "src-proxy"
          cargo build --release
          cd "../src-elevated-register"
          cargo build --release
          cd ..

          cd "src-tauri\sidecars"
          ls
          cd "..\.."

          copy "target\release\BhapticsPlayer.exe" "src-tauri\sidecars\bHapticsPlayer\BhapticsPlayer.exe"
          copy "target\release\elevated-register.exe" "src-tauri\sidecars\elevated-register.exe"

      - name: List sidecar files
        if: runner.os == 'Linux'
        shell: bash
        run: ls -lR src-tauri/sidecars || true

      - name: Install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
